### ISSUE TITLE
Kill old process when pressing cmd+r

### ISSUE THREAD

**Issue by stefan-balke** [fiveisprime/atom-make-runner#12]
First of all: Thank you for your work. This plugin is really useful.

I use it to build my latex sources. However, when I build latex-tikz pictures with errors in the source code, the process will never terminate. If I want to proceed, I have to kill the process manually like this
   kill `ps -ax | grep latex | awk '{print $1}' | sed -n 1p`
or
   killall latex

Is there a way to force the make-runner to kill all previous tasks when pressing cmr+r?

Would be great!

Thanks!

**Comment by dschwen** [comment]
Yes, this should be implemented. I'll look into it.
