### ISSUE TITLE
Keybindings don't work under Linux

### ISSUE THREAD

**Issue by dschwen** [fiveisprime/atom-make-runner#18]
The `Ctrl-R` keybinding does not work (at least under Linux). `Ctrl-Shift-R` works, but is also bound to _Symbol View: Toggle Project Symbols_

I really haven't found out a good solution for this yet. We may have to pick a completely different binding. Input welcome.

**Comment by egorse** [comment]
@dschwen - you may disable 'symbols-view' trough Settings->Packages - then Ctrl-R works fine and no needs to dance around the keybinding configuration.

**Comment by dschwen** [comment]
That is not really a solution, but merely a workaround. We simply cannot start telling people to switch off packages just to get the keybindings to work properly.

A better approach are platform specific keybindings. But I'm not too happy about those either. I can live with CMD->CTRL when going from Mac to Linux, but often keybindings have to change even more.

**Comment by egorse** [comment]
Well, keybindings management should be addressed to atom itself, not to the plugins. There is no way to plugin ensure no other plugin takes same combo

**Comment by dschwen** [comment]
Yes, good point, Sergey. But we should at least try to avoid collisions
with core modules.

**Comment by tito** [comment]
In order to fix that, you can:

- Open the command panel (Ctrl+Shift+P)
- Type "keymap", then select "Application: Open Your Keymap"
- In the file, add:
    '.platform-linux atom-text-editor':
      'ctrl-r': 'make-runner:run'
- Save, and try

There is an easy way to debug keybinding. Hit "Ctrl + ;". A pane will open in the bottom. Then do your keybinding ("Ctrl + r"), and you'll see which is the rule used first. Then you know how to map in your keycson.

**Comment by dschwen** [comment]
No, the _right_ solution is to set up platform specific keybindings, like I did [here](https://github.com/dschwen/switch-header-source/blob/master/keymaps/switch-header-source.cson). I'll make a PR.
