### ISSUE TITLE
Close on succeedd destroys the panel rather than hiding it

### ISSUE THREAD

**Issue by dschwen** [fiveisprime/atom-make-runner#26]
This causes further runs of make to throw an error ```scrollHeight of undefined```. I have a fix for this.

**Comment by dschwen** [comment]
I pushed it to the same PR that fixes the keybinding.

**Comment by dschwen** [comment]
I didn't see that you already merged it. I'll make a new PR.

**Comment by fiveisprime** [comment]
Sorry about that, I try not to let PRs sit around for long. :)

Thanks again, Daniel.

**Comment by dschwen** [comment]
Ha, that is fine, 14h is hardly long in the grand scheme of things. :-)
