### ISSUE TITLE
Error formatting is broken

### ISSUE THREAD

**Issue by dschwen** [fiveisprime/atom-make-runner#30]
Needs ```white-space: pre``` and escaping of ```<``` and ```>``` (C++ templates for example)

**Comment by egorse** [comment]
@dschwen  - I wonder, if there is the way to output html out of Makefile?

I've been using ```@echo "<B>Build Done!</B>"``` and now I can see only ```<B>Build Done!``` not bold nor having closing tag

**Comment by dschwen** [comment]
Yeah... That PR has a few issues. Looks like I'm escaping too much. I see a few &lt; &gt; in my output now. I'll have a look.
