### ISSUE TITLE
It should be possible to resize the output pane

### ISSUE THREAD

**Issue by aknuds1** [fiveisprime/atom-make-runner#7]
When running Make via this plugin in Atom 0.124.0 on OS X 10.9.4, I see that the Make output pane takes up about half of the editor's height, and I cannot resize it.

Please make it possible to resize the Make output pane.

**Comment by dschwen** [comment]
Visibility can be toggled with Shift-Ctrl-R

**Comment by dschwen** [comment]
Well, we probably can make it resizable. I'll take a look at this.
